ScuffleCloud/scuffle

.github/workflows/clean-cache.yml
Cargo.toml

Previous commit had a clear cache tool, which allowed CI to auto purge cached branches, however it did not have the write perm.
Also removing LTO and ticketing it to benchmark later. See #45 for more details.

Fix small mistakes from last PR

---

Cargo.lock
backend/api/Cargo.toml
backend/api/build.rs

The proto compiler needs the special flag `--experimental_allow_proto3_optional` to compile our `.proto` files. The same code is used in the edge, ingest and transcoder build scripts.

fix: proto compiler call in api build script

---

Cargo.lock
frontend/player/.eslintignore
frontend/player/.prettierignore
video/ingest/src/ingest/connection.rs
video/transcoder/Cargo.toml
video/transcoder/src/tests/global.rs
video/transcoder/src/tests/transcoder/mod.rs
video/transcoder/src/transcoder/job/mod.rs
video/transcoder/src/transcoder/job/utils.rs
video/transcoder/src/transcoder/job/variant/mod.rs
video/transcoder/src/transcoder/mod.rs

Adds very basic test for transcoder to validate that it works.
works on #86 point 2
- [x ] I have read the [CONTRIBUTING](https://github.com/ScuffleTV/scuffle/blob/main/CONTRIBUTING.md) doc
-_-

Transcoder Tests

---

backend/api/src/api/v1/gql/subscription/chat.rs
backend/api/src/api/v1/gql/subscription/user.rs
backend/api/src/grpc/health.rs
common/src/rmq.rs
video/edge/src/grpc/health.rs
video/ingest/src/grpc/health.rs
video/ingest/src/grpc/ingest.rs
video/ingest/src/tests/ingest.rs
video/transcoder/src/grpc/health.rs
video/transcoder/src/transcoder/job/mod.rs
video/transcoder/src/transcoder/job/track_parser.rs
video/transcoder/src/transcoder/job/utils.rs

This PR uses a tip provided in https://github.com/tokio-rs/async-stream/issues/68 to force rust format to format the code.

chore: fix formatting

---

backend/api/src/api/middleware/auth.rs
backend/api/src/api/v1/gql/handlers.rs
backend/api/src/api/v1/gql/request_context.rs
backend/api/src/api/v1/gql/subscription/user.rs
backend/api/src/grpc/api.rs
video/container/flv/src/tests/demuxer.rs
video/transcoder/src/transcoder/job/variant/mod.rs
video/transmuxer/src/codecs/hevc.rs
video/transmuxer/src/lib.rs

Nightly fmt allows for formatting rust let else expressions.

chore: reformat using nightly fmt

---

frontend/website/src/components/side-nav/streamer-card.svelte
frontend/website/src/components/stream-preview.svelte
frontend/website/src/components/top-nav.svelte

- Fixed the side bar. It was buggy in Firefox before because the avatar width wasn't limited.
- Fixed some spacing issues related to stream previews.
- Fixed spelling.

fix(webite): fix some css

---

common/src/dataloader/cache.rs

Removes the unsafe code around cache upcasting by introducing traited functions `as_ref` and `as_mut` on the AutoImplCacheRef trait. Also no longer requires the `unsafe` attribute.

fix: unsound cache upcast

---

Cargo.lock
Cargo.toml
common/Cargo.toml
config/config/Cargo.toml
config/config_derive/Cargo.toml
platform/api/Cargo.toml
proto/Cargo.toml
video/api/Cargo.toml
video/common/Cargo.toml
video/edge/Cargo.toml
video/edge/src/edge/mod.rs
video/ingest/Cargo.toml
video/ingest/src/ingest/mod.rs
video/ingest/src/tests/global.rs
video/lib/aac/Cargo.toml
video/lib/amf0/Cargo.toml
video/lib/av1/Cargo.toml
video/lib/bytesio/Cargo.toml
video/lib/flv/Cargo.toml
video/lib/h264/Cargo.toml
video/lib/h265/Cargo.toml
video/lib/mp4/Cargo.toml
video/lib/rtmp/Cargo.toml
video/lib/transmuxer/Cargo.toml
video/player/Cargo.toml
video/player_types/Cargo.toml
video/transcoder/Cargo.toml

This commit switches to using rustls over openssl. Unfortunately, rust-jwt needs openssl for the PKeyVerify impl, so we also forked their repo to add support for openssl-vendored which means that it will be staticly linked rather than a system-dep. This feature is only used by video-edge and lto-fat purges it from all other binaries.
Describe the big picture of what you want to change here, to help the maintainers understand why we should accept this pull request. Be sure to link to the issue if it fixes a bug or resolves a feature request.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …

Remove OpenSSL

---

Cargo.lock
common/src/task.rs
platform/image_processor/Cargo.toml
platform/image_processor/src/config.rs
platform/image_processor/src/processor/error.rs
platform/image_processor/src/processor/job/decoder/ffmpeg.rs
platform/image_processor/src/processor/job/mod.rs

Allow for the input path to be an http url which the image processor will fetch when processing the image.

feat(platform/image-processor): allow http downloads on image processor

---

platform/api/src/api/v1/gql/queries/mod.rs

Fix search queries. I forgot to test them when reviewing the sqlx refactor pr.

fix(platform): search query

---

.editorconfig
.vscode/extensions.json
crates/batching/README.md
crates/context/README.md
crates/ffmpeg/README.md
crates/http/README.md
crates/metrics/README.md
crates/postcompile/README.md
crates/pprof/README.md
crates/settings/README.md
crates/signal/README.md

- Fixes some copy paste mistakes in the readmes
- Removes a deprecated vscode plugin recommendation
- Adds other useful vscode plugin recommendations
- Fixes editorconfig for markdown files

docs: fixes

---

.github/workflows/orphaned.yaml

Adds a github action that finds differences in PRs that are not in the final PR diff.
For example if 
`Commit A` [**`adds random.bin`**](#)
`Commit B` [**`removes random.bin`**](#)
`Commit C` [**`changes x.py`**](#)
The final PR diff will only show the changes for `x.py` and the `random.bin` addition and removal will not be shown. This action finds and reports those and other line diffs so that we can understand if something has been secretly inserted into git history.

add orphaned diff finder

---

Cargo.lock
Justfile
crates/batching/Cargo.toml
crates/batching/README.md
crates/batching/src/lib.rs
crates/context/Cargo.toml
crates/context/README.md
crates/context/src/lib.rs
crates/metrics/derive/Cargo.toml
crates/metrics/derive/src/lib.rs
crates/workspace-hack/Cargo.toml

fix: doc tests

---

.github/workflows/ci.yaml
Justfile

Fix a cache issue with doc tests and enable them with ci.
We remove branch coverage here, unfortunately branch coverage is a bit broken. We will have to remove it anyways because it does not work with diesel. Noted by https://github.com/llvm/llvm-project/issues/119558, disabling it now is fine. I hope we can enable it later at somepoint to get back the branch coverage.

fixes doc testing in CI

---

.github/workflows/ci.yaml
Justfile

For some reason cargo llvm-cov report does not include doc coverage even if the doc coverage profraw files are there. It seems you also need to
add the flag `--doctests` to the report command.
I opened an upstream issue to see if this is the desired behaviour or not. It seems a bit unintuitive.
https://github.com/taiki-e/cargo-llvm-cov/issues/412

fix doc coverage bug

---

Cargo.lock
Cargo.toml
crates/bytesio/Cargo.toml
crates/bytesio/src/tests/errors.rs
crates/future-ext/Cargo.toml
crates/future-ext/src/lib.rs
crates/http/Cargo.toml
crates/http/src/backend/quic/quinn/serve.rs
crates/http/src/backend/tcp/serve.rs
crates/rtmp/Cargo.toml
crates/rtmp/src/session/server_session.rs
crates/rtmp/src/tests/rtmp.rs
crates/signal/Cargo.toml
crates/signal/src/lib.rs

I find the syntax for `tokio::time::timeout` to be quite ugly, since it breaks the typical chained method calls. With the FutureExt trait we can just call `.with_timeout(..)` instead which seems to be a cleaner way to do it.

add future-ext

---

Cargo.lock
crates/context/src/lib.rs
crates/signal/Cargo.toml
crates/signal/README.md
crates/signal/src/bootstrap.rs
crates/signal/src/lib.rs

- Improve test coverage
- Improve docs by adding examples

scuffle-signal: test coverage and docs

---

crates/h264/src/sps.rs
crates/h264/src/tests.rs

The SPS parser panics when num_units_in_tick is 0. Included a test to ensure it doesn't happen again :)

Fix h264 num_units_in_tick divide by zero

---

.github/workflows/ci.yaml
Justfile

the latest nightly broke on coverage checking so we pin it back to continue working. We will unpin it after nightly has been fixed.

revert nightly to older build

---

crates/aac/Cargo.toml
crates/aac/LICENSE.Apache-2.0
crates/aac/LICENSE.MIT
crates/aac/README.md
crates/aac/src/lib.rs

setup the create to be ready to publish

adds a readme and licenese for the aac crate

---

crates/ffmpeg/src/encoder.rs

there is a use after free in `encoder::Encoder::new` when codec-specific options are used
don't use after free

fix: use after free in ffmpeg 

---

Cargo.lock
Cargo.toml
crates/av1/Cargo.toml
crates/av1/LICENSE.Apache-2.0
crates/av1/LICENSE.MIT
crates/av1/README.md
crates/av1/src/config.rs
crates/av1/src/lib.rs
crates/av1/src/obu/mod.rs
crates/av1/src/obu/seq.rs
crates/av1/src/obu/utils.rs
crates/bytes-util/src/bit_write.rs
crates/bytes-util/src/bytes_cursor.rs
crates/flv/Cargo.toml
crates/flv/src/define.rs
crates/flv/src/flv.rs
crates/flv/src/tests/demuxer.rs
crates/mp4/Cargo.toml
crates/mp4/src/boxes/types/av01.rs
crates/mp4/src/boxes/types/av1c.rs
crates/mp4/src/tests/demux.rs
crates/transmuxer/Cargo.toml
crates/transmuxer/src/codecs/av1.rs
crates/transmuxer/src/define.rs

Moves av1 stuff into a new crate for av1 decoding, encoding & obu parsing. 
Improves test coverage on existing av1 parsing.
Improves parse design making use of zero copy behaviour. 
Remove `scuffle_bytes_util::BytesCursorExt::remaining()` fn because it conflicts with an already existing more generic impl from `Bytes::Buf`.
CLOUD-25

cleanup scuffle-av1 header decoder

---

crates/amf0/src/decode.rs
crates/amf0/src/encode.rs

Improve code coverage for amf0 crate by adding more tests
I added more tests to the amf0 crate, specifically in encode.rs and decode.rs
n/a

improved test coverage for amf0 tests

---

Cargo.lock
Justfile
crates/av1/Cargo.toml
crates/bootstrap/Cargo.toml
crates/bootstrap/derive/Cargo.toml
crates/ffmpeg/Cargo.toml
crates/ffmpeg/src/dict.rs
crates/ffmpeg/src/io/channel.rs
crates/ffmpeg/src/io/input.rs
crates/ffmpeg/src/io/internal.rs
crates/ffmpeg/src/io/output.rs
crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__input__tests__receive_packet.snap
crates/ffmpeg/src/lib.rs
crates/ffmpeg/src/packet.rs
crates/ffmpeg/src/stream.rs
crates/workspace-hack/Cargo.toml

Added test coverage to ffmpeg io files.
I added tests, and one function for the dictionary file for testing purposes (just to check if it's empty). Note that I was unable to figure out how to make tests for the `io/output.rs` file, namely the `write_xyz()` functions.
There was one strange case I ran into with the `flags()` function which returned a value of `2097152`. I did my best to look into it but I have no idea why it does that, so I left the test commented out in the file.
n/a

added test coverage for ffmpeg io

---

Cargo.lock
crates/postcompile/Cargo.toml
crates/postcompile/README.md
crates/postcompile/src/lib.rs
crates/postcompile/src/snapshots/postcompile__tests__compile_failure.snap
crates/postcompile/src/snapshots/postcompile__tests__compile_success.snap

- Adds docs
- Adds tests and improves coverage
- I'm not sure how to cover the remaining lines in postcompile since most of them are related to failing rustc and cargo commands. There is not a reliable way to crash rustc or cargo as far as I know.
CLOUD-13

postcompile: docs and tests

---

crates/aac/src/lib.rs
crates/av1/src/lib.rs
crates/batching/src/lib.rs
crates/bootstrap/src/lib.rs
crates/bootstrap/telemetry/src/lib.rs
crates/context/src/lib.rs
crates/expgolomb/src/lib.rs
crates/flv/src/lib.rs
crates/metrics/derive/src/lib.rs
crates/metrics/src/lib.rs
crates/signal/src/lib.rs

- Removes headlines from crate root docs
Otherwise it would look like this when rendered:
CLOUD-35

docs: clean up

---

crates/rtmp/src/tests/rtmp.rs

- Introduces a workaround for the failing rtmp test

fix: rtmp test workaround

---

crates/pprof/Cargo.toml
crates/pprof/README.md
crates/pprof/src/cpu.rs
crates/pprof/src/lib.rs
crates/signal/src/lib.rs

- Adds a simple test
- Improves docs
CLOUD-11

pprof: add test and docs

---

Cargo.toml

This is a small fix that allows this crate to be used correctly via a git dep.

fix path for workspace hack dep

---

codecov.yml

We dont need codecov to fail a commit if the coverage doesnt meet the thresholds.

disable code cov status check

---

README.md

Updates Github Actions status checks badge to be correct. Note that this also changes the behavior of clicking the icon to link to checks of specifically the main branch.
Previous appearance:
Fixed appearance:
Also the updated version allows for checking specific check runs if we want to use that in the future: https://shields.io/badges/git-hub-branch-check-runs

updated readme github actions badge

---

crates/ffmpeg/src/decoder.rs
crates/ffmpeg/src/log.rs

Fixes 2 memory leaks in unit tests.
found using:
`CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="valgrind --error-exitcode=1 --leak-check=full" cargo nextest run -p scuffle-ffmpeg`
Rust does not run destructors of static variables therefore we need to manually unset the log callbacks when we add them.

fix: memory leaks in ffmpeg tests

---

crates/ffmpeg/CHANGELOG.md
crates/ffmpeg/src/log.rs
crates/ffmpeg/src/scaler.rs

fixes #282 
This build fixes the small issues with the windows build for ffmpeg. We don't officially support windows builds on any of our crates yet. That will not be done in this PR, there is a more compressive ticket for that CLOUD-58.
We do not officially support windows, we don't run tests / memory checks against our libraries on windows. Therefore even though it compiles safety is not guaranteed. After CLOUD-58 is completed we can assert that windows is correct.

fix windows for ffmpeg build

---

.github/actions/setup-ffmpeg/action.yaml
.github/actions/setup-rust/action.yaml
.github/patch-docs.sh
.github/workflows/ci.yaml
.github/workflows/crate-release.yaml
crates/bootstrap/telemetry/Cargo.toml
crates/bootstrap/telemetry/src/lib.rs
crates/settings/Cargo.toml
crates/settings/src/lib.rs

Moves the clippy powerset stuff into the clippy job (only runs on a brawl run) and then adds a new job that runs `cargo package`. Cargo Package is a tool ran before `cargo publish` (it runs automatically unless you do `--no-verify`). This is a sanity check to test if the crate compiles before uploading it to crates.io. The reason we do this in a power-set is because we want to make sure that all features of the crate compile successfully. This is a known issue on crates.io where sometimes crates break and or dont work depending on the features they are enabled with.
CLOUD-63
This PR also splits our ci into components, to reuse existing setup code related to `setup-rust` where we install the rust tool chain, use a cache and install custom rust tools. As well as `setup-ffmpeg` where we …

CI Improvements

---

.github/labels.yaml
.github/workflows/cargo-release-pr.yaml

Adds a `release` and a `automated` label for the release prs generated via ci. We also attach the `no-changelog-required` label to the PR since it wont include a changelog.

add new labels for release prs

---

CODEOWNERS

The first ones are ignored if later ones overrule.

fix code owners order

---

changes.d/pr-303.toml
crates/ffmpeg/src/filter_graph.rs
crates/ffmpeg/src/frame.rs
crates/ffmpeg/src/lib.rs
crates/ffmpeg/src/rational.rs
crates/ffmpeg/src/resampler.rs
crates/ffmpeg/src/scaler.rs

- fixes potential undefined behavior when using frame types
- makes creating and using frame types easier
- interpreting and manipulating pixel and sample data is still unwieldy and requires user intervention, often with unsafe code
- new `Resampler` type, with `libswresample` functionality

improve ffmpeg API

---

crates/http/Cargo.toml
crates/workspace-hack/Cargo.toml
deny.toml

ring is unmaintained
we do not use ring for anything except for http3 testing in scuffle-http. Unfortunately reqwest uses ring for http3.
See https://github.com/seanmonstar/reqwest/issues/2566

add ignore for RUSTSEC-2025-0007

---

crates/flv/src/lib.rs
crates/h264/README.md

In the test we incorrectly use `Sps::parse` and instead should be using `Sps::parse_with_emulation_prevention`. Also corrects the README.md docs to do the same.

fix missed test case in h264 pr

---

Justfile

This changes the shebangs in the Justfile from `#!/bin/bash` to `#/usr/bin/env bash` which is more portable across systems.
`/bin/bash` doesn't exist on e.g. nixOs, most BSDs, Alpine and apparently newer versions of macOs use a very old version of bash at `/bin/bash`.

Change shebangs in Justfile from '/bin/bash/' to '/usr/bin/env bash'

---

crates/http/src/server.rs

Nightly got bumped and caused an update in clippy. 
I suspect in 2024 edition the behaviour around the pin! macro changed because I believe you used to require the variable be mut before using the macro.

fix clippy warning from nightly

---

.github/labels.yaml
.github/workflows/cargo-update.yaml
.github/workflows/release.yaml

Some minor ci fixes
- fixed deploy env name on crates release to be where the crates are published to (crates.io)
- added a new label to be `do-not-merge` when a PR should not be merged.
- fix cargo update pr labels permission

minor ci fixes

---

Cargo.lock
changes.d/pr-440.toml
crates/amf0/Cargo.toml
crates/amf0/src/de/mod.rs
crates/amf0/src/ser.rs
crates/bootstrap/Cargo.toml
crates/bootstrap/examples/cli.rs
crates/flv/Cargo.toml
crates/flv/src/script.rs
crates/flv/src/video/body/enhanced/metadata.rs
crates/postcompile/Cargo.toml
crates/postcompile/src/features.rs
crates/rtmp/Cargo.toml
crates/rtmp/src/command_messages/mod.rs
crates/rtmp/src/command_messages/netconnection/mod.rs
crates/rtmp/src/command_messages/netstream/mod.rs
crates/rtmp/src/command_messages/on_status/mod.rs
crates/settings/Cargo.toml
crates/settings/examples/cli.rs
crates/settings/src/lib.rs
dev-tools/xtask/Cargo.toml
dev-tools/xtask/src/cmd/change_logs/util.rs
dev-tools/xtask/src/cmd/power_set/utils.rs

Uses `serde_derive` instead of serde's derive feature for improved compile times.
CLOUD-98

Use serde_derive directly instead of serde's derive feature

---

.github/labels.yaml

Add the `stale` label to label PRs that can't be merged for a reason that can not be easily resolved or is out of our control.

chore: add stale label

---

changes.d/pr-445.toml
crates/transmuxer/src/lib.rs

Fixes a small typo from the transmuxer crate.

Fix variable name typo in transmuxer crate

---

Cargo.lock
crates/ffmpeg/CHANGELOG.md
crates/ffmpeg/Cargo.toml
crates/ffmpeg/src/enums/av_codec_id.rs

feature gate 2 flags to fix ffmpeg's builds.
https://docs.rs/crate/scuffle-ffmpeg/0.3.1/builds/2114088
CLOUD-61

fix ffmpeg docs

---

changes.d/pr-496.toml
crates/amf0/src/de/mod.rs
crates/amf0/src/decoder.rs
crates/amf0/src/ser.rs
crates/mp4/src/codec.rs
crates/tinc/build/src/codegen/cel/compiler/mod.rs
crates/tinc/cel/src/lib.rs
crates/tinc/src/private/error.rs
dev-tools/xtask/src/cmd/release/utils.rs
rustfmt.toml

Update the fmt style to always expand enum struct variants to be multi-line.
Reasoning: if I wanted a single line, I likely would have defined it as a tuple variant.

update fmt style

---

cloud/core/src/bin/standalone.rs
cloud/core/src/dataloaders/organizations.rs
cloud/core/src/dataloaders/users.rs

Dataloaders should get a copy of the pool so that they can run concurrently over a set of requests.

fix: dataloaders should get a copy of the pool

---

Cargo.lock
changes.d/pr-610.toml
cloud/core/cedar/Cargo.toml
cloud/core/emails/Cargo.toml
cloud/email/Cargo.toml
cloud/ext-traits/Cargo.toml
crates/aac/Cargo.toml
crates/bytes-util/Cargo.toml
crates/ffmpeg/Cargo.toml
crates/flv/Cargo.toml
misc/utils/rust/analyzer/discover/Cargo.toml
misc/utils/rust/doc/merger/Cargo.toml
misc/utils/rust/doc/test/builder/Cargo.toml
misc/utils/rust/doc/test/common/Cargo.toml
misc/utils/rust/sync_readme/Cargo.toml
vendor/cargo/defs.bzl

This PR fixes the normal cargo build and removes unused dependencies that I found using [cargo-udeps](https://github.com/est31/cargo-udeps).

fix: cargo build and remove unused dependencies

---

cloud/core/src/common.rs
cloud/core/src/operations/login.rs
cloud/core/src/services.rs

This PR fixes the Google login for emails that are already registered with us but not associated with a Google account yet. When someone logs in with a Google account which is not linked to a Scuffle user and whose email matches one that is already on record, the Google account will get linked to that existing account now.

fix(core): google login for non-google users
