- .github/workflows/sync-labels.yml
fixes workflow permissions
-/-
> build(workflow): label sync

- .github/workflows/sync-labels.yml
fixes workflow permissions v2
-/-
> build(workflow): label sync fix

- CONTRIBUTING.md
- README.md
- design/README.md
- design/cdn-edge.md
- design/high-level.md
- design/video-infrastructure.md
Some sentences were changed or rewritten to improve readability. Also, some spelling mistakes and minor errors were corrected.
Closes #11
> style(docs): spelling errors and grammar fixed

- CODE_OF_CONDUCT.md
Code of Conduct based on version [2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html); slightly modified
E-Mail conduct@scuffle.tv needs to be set up
> Implementation of the Code of Conduct

- CLA.md
- CONTRIBUTING.md
Describe the big picture of what you want to change here, to help the maintainers understand why we should accept this pull request. Be sure to link to the issue if it fixes a bug or resolves a feature request.
> doc(legal): add CLA to repo, update contributing

- .github/SECURITY.md
Security vulnerability reporting instructions for Scuffle
E-Mail [security@scuffle.tv](mailto:security@scuffle.tv) needs to be set up
___
Closes #17
> Implementation of SECURITY.md

- CODEOWNERS
start setting up code owners for GitHub/reviewing. view more here: https://github.blog/2017-07-06-introducing-code-owners/
Closes #31 
adding the `CODEOWNERS` file that automatically assigns a team to a pull request if it edits a file that is owned by said team.
> Add GitHub code owners

- .github/workflows/lint-test-build.yml
- .gitignore
- .vscode/extensions.json
- docker/build.Dockerfile
- maskfile.md
Adding code coverage for PRs.
Closes #50 
Adding code coverage will force us to test our code.
> chore: add code coverage

- CONTRIBUTING.md
Many providers do not install these packages - So they have to be installed afterwards
-/-
> Adding missing packages to  CONTRIBUTING

- backend/api/src/api/v1/gql/auth.rs
- backend/api/src/api/v1/gql/mod.rs
- backend/api/src/api/v1/middleware/auth.rs
- backend/api/src/dataloader/mod.rs
- backend/api/src/dataloader/session.rs
- backend/api/src/dataloader/user.rs
- backend/api/src/global/mod.rs
- backend/api/src/gql.nocov.rs
- backend/api/src/main.rs
- backend/api/src/tests/api/v1/gql/auth.rs
- backend/api/src/tests/api/v1/gql/models/user.rs
- backend/api/src/tests/api/v1/middleware/auth.rs
- backend/api/src/tests/dataloader/mod.rs
- backend/api/src/tests/dataloader/session.rs
- backend/api/src/tests/dataloader/user.rs
- backend/api/src/tests/global/mod.rs
- backend/api/src/tests/mod.rs
- sqlx-data.json
Dataloaders allow us to batch queries across requests which in turn make it very optimized at scale. Using the `WHERE id IN ANY($1)` SQL feature allows us to combine many queries into a single query which makes it very efficient at high concurrency requests.
We should also investigate how we can take advantage of redis caching to speed up results. The main issue with redis caching is how do we uncache stale data. Results need to be fresh always, that is a MUST there is no way we can serve stale data. So redis caching becomes a complex mess because invalidating cached data is very hard.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
> Dataloaders

- backend/api/src/api/v1/gql/playground.html
fix resource integrity for `graphiql.min.js` from https://unpkg.com
[OWASP Top 10 2021 Category A8](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/) - Software and Data Integrity Failures
[MITRE, CWE-353](https://cwe.mitre.org/data/definitions/353) - Missing Support for Integrity Check
[OWASP Top 10 2017 Category A6](https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A6-Security_Misconfiguration.html) - …
> fix: graphiql resource integrity

- backend/api/src/api/error.rs
- backend/api/src/api/v1/gql/auth.rs
- backend/api/src/api/v1/gql/error.rs
- backend/api/src/api/v1/gql/handlers.rs
- backend/api/src/api/v1/gql/mod.rs
- backend/api/src/api/v1/middleware/auth.rs
- backend/api/src/config.rs
- backend/api/src/global/turnstile.rs
- backend/api/src/tests/api/errors.rs
- backend/api/src/tests/api/v1/gql/auth.rs
- backend/api/src/tests/api/v1/gql/errors.rs
- common/src/types/session.rs
Implementing some of the minor changes discussed in my review of PR #63 
- https://github.com/ScuffleTV/scuffle/pull/63#discussion_r1126619829
- https://github.com/ScuffleTV/scuffle/pull/63#discussion_r1126094642
- https://github.com/ScuffleTV/scuffle/pull/63#discussion_r1126636700
- https://github.com/ScuffleTV/scuffle/pull/63#discussion_r1126325355
- https://github.com/ScuffleTV/scuffle/pull/63#discussion_r1126338350
Time to sign that CLA …
> Small refactor

- docker/website.Dockerfile
Update the website docker image
- x -
> Fix website CVE docker build

- .github/ISSUE_TEMPLATE/bugreport.yml
This fixes spelling to make it clearer to the submitter what we are asking.
- [] Bugfix (non-breaking change which fixes an issue)
> fix: spelling

- docker/website.Dockerfile
> fix: docker website build

- backend/api/src/api/v1/gql/playground.html
I updated the integrity hashes in the GQL playground and pinned the package versions so this won't happen again.
> Fix GQL playground

- Cargo.lock
- video/transcoder/src/config.rs
- video/transcoder/src/transcoder/job/mod.rs
Remove env variables and change the UID and GID of the ffmpeg process.
completes #86 part 3
> [Transcoder] restrict ffmpeg process

- Cargo.lock
- backend/api/Cargo.toml
- backend/api/build.rs
- backend/api/src/api/v1/gql/error.rs
- backend/api/src/api/v1/gql/mod.rs
- backend/api/src/api/v1/gql/models/user.rs
- backend/api/src/api/v1/gql/subscription/mod.rs
- backend/api/src/api/v1/gql/subscription/user.rs
- backend/api/src/config.rs
- backend/api/src/global/mod.rs
- backend/api/src/gql.nocov.rs
- backend/api/src/main.rs
- backend/api/src/pb.rs
- backend/api/src/subscription.rs
- backend/api/src/tests/api/v1/gql/mod.rs
- backend/api/src/tests/api/v1/gql/subscription.rs
- backend/api/src/tests/global/mod.rs
- proto/scuffle/types/api_events.proto
- schema.graphql
This addresses the second point in #87 
This adds support for GQL pubsub event subscriptions for various events.
> feat: gql pubsub event subscriptions

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/logging.rs
- frontend/website/package.json
- frontend/website/pnpm-lock.yaml
- package.json
- pnpm-lock.yaml
Patches for fred: https://github.com/ScuffleTV/fred.rs
Patches for tracing: https://github.com/ScuffleTV/tracing
We will remove these patches when the upstreams fix their versions
> chore: bump patch external crates

- CONTRIBUTING.md
- frontend/player/.eslintignore
- frontend/player/.gitignore
- frontend/player/.prettierignore
- frontend/website/.eslintignore
- frontend/website/.prettierignore
- frontend/website/README.md
- maskfile.md
- Update docs to mention pnpm instead of yarn.
- Update `DATABASE_URL` env.
> docs: update yarn mentions to pnpm

- config/config/examples/derive.rs
- config/config/src/error.rs
- config/config/src/key.rs
- config/config/src/lib.rs
- config/config/src/sources/file/mod.rs
- config/config/src/sources/manual.rs
- config/config/src/sources/mod.rs
- config/config_derive/src/lib.rs
- config/config_test/src/tests.rs
- Resolves #103 by providing a new source called `ManualSource` which a `ConfigBuilder` always has at least one of
- Fixes a few bugs
> feat: config improvements

- platform/website/src/components/player.svelte
- platform/website/src/routes/+page.svelte
Fixes some minor design problems on front page.
> fix: minor design fixes

- platform/website/src/components/top-nav.svelte
- platform/website/src/routes/+layout.svelte
Shows dev banner when server runs in dev mode.
> feat(website): add dev banner

- platform/website/src/components/dev-banner.svelte
- platform/website/src/routes/+layout.svelte
- platform/website/vite.config.ts
Adds debug dialog.
Toggle with `Ctrl+Alt+Shift+D`.
> feat(website): add debug dialog

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- common/src/ratelimiter/mod.rs
- common/src/ratelimiter/ratelimit.lua
- common/src/tests/mod.rs
- common/src/tests/ratelimiter.rs
- dev/docker-compose.yml
- maskfile.md
Adds a ratelimiter generic to common
There will be a future PR implementing this in video / platform.
> Add RateLimiter Lua

- platform/api/src/api/request_context.rs
- platform/api/src/api/v1/gql/guards.rs
- platform/api/src/api/v1/gql/handlers.rs
- platform/api/src/api/v1/gql/models/channel.rs
- platform/api/src/api/v1/gql/models/user.rs
- platform/api/src/api/v1/gql/mutations/auth.rs
- platform/api/src/api/v1/gql/mutations/chat.rs
- platform/api/src/api/v1/gql/mutations/user.rs
- platform/api/src/api/v1/gql/mutations/user/two_fa.rs
- platform/api/src/api/v1/gql/queries/user.rs
- platform/api/src/api/v1/gql/subscription/channel.rs
- platform/api/src/api/v1/gql/subscription/user.rs
- platform/api/src/database/two_fa_request.rs
Since websocket connections live longer, auth might have expired by the time they make a request. So we have to validate auth on each request.
fixes #145 
> fix websocket auth

- platform/website/src/components/player.svelte
- platform/website/src/routes/[username]/+page.svelte
I noticed that the player height was bugged when the top nav is hidden (e.g. in theater mode)
> fix(website): player height

- platform/api/src/video_event_handler.rs
- platform/migrations/20230825170300_init.up.sql
- platform/website/src/components/channel/title.svelte
- platform/website/src/components/side-nav/streamer-card.svelte
- Fixes `channel_live_viewer_count` column in `users` table
- Fix "null" being shown as stream title instead of nothing
> fix(platform): small fixes

- .github/labels.yml
- .github/workflows/sync-labels.yml
Now the workflow for the `Sync Lables` is corectly configured.
For faster performance, we configured the **fetch-depth** option and set the depth to 1. This allows for faster pulling of the repository, resulting in improved performance.
The color values on GitHub pages for adding labels are always in uppercase. The original color has not changed, it remains the same.
Double quotes for the name and description are not needed in this file, they have been removed.
The labels are sorted in ascending order within the particular labels group, which makes it easier to locate a specific label.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
> chore: fixed paths for syncing labels

- platform/api/src/api/v1/gql/subscription/chat.rs
- platform/api/src/database/chat_message.rs
This pr adds chat history by returning a maximum of 100 messages that are not older than 10 minutes from the chat subscription endpoint.
> feat(platform): add chat history

- platform/website/src/routes/about/+page.svelte
This pr fixes a phrase on the about page.
> fix(website): about page phrasing

- common/src/http/router/mod.rs
- package.json
- platform/api/src/api/v1/gql/mod.rs
- platform/api/src/api/v1/gql/models/color.rs
- platform/api/src/api/v1/gql/mutations/user.rs
- platform/api/src/api/v1/gql/playground.html
- platform/website/codegen.cjs
- platform/website/src/components/chat/messages.svelte
- platform/website/src/components/player.svelte
- platform/website/src/components/settings/profile/color.svelte
- platform/website/src/components/side-nav.svelte
- platform/website/src/components/user/default-avatar.svelte
- platform/website/src/lib/auth.ts
- platform/website/src/lib/colors.ts
- platform/website/src/lib/gql.ts
- platform/website/src/lib/search.ts
- platform/website/src/routes/(app)/[username]/+layout.ts
- platform/website/src/routes/(app)/settings/profile/+page.svelte
- pnpm-lock.yaml
- schema.graphql
- video/player/src/player/runner/ext/drive.rs
- video/player/src/player/runner/mod.rs
This pr includes multiple bug fixes for the website.
This is a little late because I forgot about this branch.
> fix(website): some minor fixes

- .github/workflows/lint-test-build.yml
build(runner): set runs-on to scuffle-ci
-/-
> build(runner): set runs-on to scuffle-ci

- platform/website/src/app.html
- platform/website/src/routes/about/+page.ts
This fixes the title bug (#194) and sets the svelte `prerender` option for the about page.
Closes #194
> fix(website): title bug and prerender

- .github/workflows/ci.yaml
- .github/workflows/gh-cache.yaml
Currently the merge queue feature kinda sucks:
- You are unable to change the commit description
- Jobs run sometimes?
- We should likely make our own at some point to run a 2nd stage of ci.
-_-
> disable merge queue

- README.md
I noticed some strange issues with the readme on hover of the badges.
> Attempt to make the readme cleaner

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- Justfile
- crates/context/Cargo.toml
- crates/context/README.md
- crates/context/src/ext.rs
- crates/context/src/lib.rs
- crates/future-ext/Cargo.toml
- More and improved docs
- Improve internal code structure
- Add tests and coverage
Closes ALL-5
> scuffle-context: small refactor, tests and docs

- .github/workflows/ci.yaml
unpin the nightly pin introduced by #242 since nightly has now been fixed
> unpin nightly

- LICENSE.AGPL-3.0
- LICENSE.Apache-2.0
- LICENSE.MIT
> bump license copyright year

- .github/patch-docs.sh
- .github/workflows/ci.yaml
- .github/workflows/docs-release.yaml
- Adds CI step to insert custom html into the docs
> feat(ci): add custom html step for docs

- .github/workflows/ci.yaml
- Justfile
- crates/batching/src/batch.rs
- crates/ffmpeg/src/log.rs
> fix: ci clippy step

- crates/mp4/src/boxes/types/padb.rs
seems that nightly updated and there is a new lint that was added. This just lints main and fixes the ci.
> fix linting for mp4 crate

- Cargo.lock
- Cargo.toml
- crates/ffmpeg/CHANGELOG.md
- crates/ffmpeg/Cargo.toml
Bump ffmpeg version to include the windows fix
> bump ffmpeg version

- .github/workflows/ci.yaml
- .github/workflows/crate-release.yaml
- .gitignore
- Justfile
- crates/batching/Cargo.toml
- crates/batching/src/batch.rs
- crates/batching/src/dataloader.rs
- crates/bootstrap/src/global.rs
- crates/bootstrap/telemetry/Cargo.toml
- crates/bootstrap/telemetry/src/lib.rs
- crates/ffmpeg/src/scaler.rs
- crates/pprof/src/lib.rs
- crates/rtmp/Cargo.toml
- crates/rtmp/src/tests/rtmp.rs
- crates/signal/Cargo.toml
- crates/signal/src/lib.rs
- valgrind_suppressions.log
Adds valgrind to tests and CI to check for memory leaks.
CLOUD-51
> add valgrind

- .github/workflows/ci.yaml
> add powerset to ci

- .github/actions/setup-rust/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/crate-release.yaml
- .github/workflows/create-crate-release.yaml
> try ubicloud

- Cargo.lock
- changes.d/pr-366.toml
- crates/settings/Cargo.toml
- crates/workspace-hack/Cargo.toml
bumps config from 0.14 to 0.15
> bump config from 0.14 -> 0.15

- Cargo.lock
- changes.d/pr-368.toml
- crates/bootstrap/telemetry/Cargo.toml
- crates/metrics/Cargo.toml
- crates/metrics/examples/Cargo.toml
- crates/metrics/src/prometheus/mod.rs
bumps prometheus-client to 0.23
> bump prometheus-client 0.22 -> 0.23

- Cargo.lock
- changes.d/pr-367.toml
- crates/bootstrap/telemetry/Cargo.toml
- crates/bootstrap/telemetry/src/lib.rs
- crates/bootstrap/telemetry/src/opentelemetry.rs
- crates/metrics/Cargo.toml
- crates/metrics/examples/Cargo.toml
- crates/metrics/examples/src/derive.rs
- crates/metrics/examples/src/prometheus.rs
- crates/metrics/src/lib.rs
- crates/metrics/src/prometheus/mod.rs
- crates/workspace-hack/Cargo.toml
- valgrind_suppressions.log
bumps the open-telemetry stack fixing all breaking changes
> bumps open-telemetry stack 0.28 -> 0.29

- release-plz.toml
* fixes the ffmpeg release config
* removes the contributors section because its duplicated
> fix release-plz config

- crates/ffmpeg/src/encoder.rs
- crates/ffmpeg/src/log.rs
- crates/h264/src/config.rs
- crates/h264/src/sps.rs
Some previous prs ignored errors instead of bubbling (in library code) or unwrapping in test code. This pr just fixes those few mistakes that slipped through the review process.
> fix error handling on previous prs

- .github/scripts/ci-matrix-prep.py
- .github/workflows/change-log.yaml
- .github/workflows/release.yaml
fix minor ci issues missed by previous prs
> fix minor ci issues missed by previous prs

- .github/renovate.json5
We have a custom ci job to automatically update the lock file once per week.
> disable renovate lock file maintenance

- changes.d/pr-388.toml
- crates/metrics/Cargo.toml
- crates/metrics/src/collector.rs
- crates/metrics/src/lib.rs
- crates/metrics/src/prometheus/mod.rs
- crates/metrics/src/value.rs
- valgrind_suppressions.log
this pr aims to add more tests to the scuffle-metrics crate
> more tests to scuffle-metrics

- crates/http/examples/src/axum.rs
- crates/http/examples/src/simple_service.rs
- crates/http/src/backend/h3/mod.rs
- crates/http/src/backend/hyper/stream.rs
- crates/metrics/derive/src/metrics_impl.rs
- crates/mp4/src/boxes/types/subs.rs
- crates/rtmp/src/chunk/tests/decoder.rs
Seems that clippy got updated and discovered some new lints.
> fix clippy lints

- changes.d/pr-400.toml
- crates/bootstrap/derive/src/lib.rs
- crates/bootstrap/derive/src/main_impl.rs
fixed panic from running when no service is provided to scuffle-bootstrap
CLOUD-80
[CLOUD-80]: https://scuffle.atlassian.net/browse/CLOUD-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix scuffle-bootstrap no service panic

- changes.d/pr-401.toml
- crates/http/README.md
- crates/http/src/lib.rs
> fix(http): readme

- crates/ffmpeg/src/filter_graph.rs
Nightly added a new lint which causes our CI to fail.
> fix clippy lint

- dev-tools/xtask/src/cmd/workspace_deps.rs
The bug was related to how toml_edit replaces text, we should reuse the existing dep instead of creating a new one. This is likely a bug in toml_edit itself, but doing it this way avoids it on our end. :)
> fix workspace-deps xtask tool

- crates/flv/src/video/body/enhanced/metadata.rs
Rust updated added a new lint check, this updates the exisiting code to abide by this lint.
> fix new linting

- .github/workflows/release.yaml
- docs/blog/2023-07-31-navigating-ip-space-acquisition/index.mdx
- docs/blog/2023-11-03-video-paas-service-design/index.mdx
- docs/blog/authors.yml
- docs/blog/tags.yml
- docs/docusaurus.config.ts
- docs/package.json
- docs/src/components/HomepageFeatures/index.tsx
- docs/src/css/custom.css
- docs/src/pages/index.tsx
- docs/tsconfig.json
- pnpm-lock.yaml
- Disable the dark mode switch until we have a dark color palette
- Blog authors
- Blog tags
- tsconfig
- Update dependencies
> fix(docs): some things I found

- changes.d/pr-444.toml
- crates/bytes-util/src/lib.rs
- crates/bytes-util/src/range_check.rs
- crates/h264/src/sps/chroma_sample_loc.rs
- crates/h264/src/sps/mod.rs
- crates/h264/src/sps/pic_order_count_type1.rs
- crates/h264/src/sps/sps_ext.rs
- crates/h265/src/lib.rs
- crates/h265/src/nal_unit_header.rs
- crates/h265/src/sps/long_term_ref_pics.rs
- crates/h265/src/sps/mod.rs
- crates/h265/src/sps/pcm.rs
- crates/h265/src/sps/profile_tier_level.rs
- crates/h265/src/sps/sps_3d_extension.rs
- crates/h265/src/sps/sps_scc_extension.rs
- crates/h265/src/sps/st_ref_pic_set.rs
- crates/h265/src/sps/sub_layer_ordering_info.rs
- crates/h265/src/sps/vui_parameters/hrd_parameters.rs
- crates/h265/src/sps/vui_parameters/mod.rs
> Move range check to bytes-util + use it in h264

- Cargo.lock
somehow didnt include lock commit
> fix missing lock from previous pr

- dev-tools/xtask/src/cmd/semver_checks/mod.rs
Fixes a bad unwrap as seen in: https://github.com/ScuffleCloud/scuffle/actions/runs/14829284811/job/41627342997#step:8:282
~~Currently based off of Troy's tinc branch to make sure it works.~~ I'm pretty sure it works now
> Fix semver checks bad unwrap

- Cargo.lock
- changes.d/pr-416.toml
- changes.d/pr-452.toml
- crates/http/Cargo.toml
- crates/http/src/backend/h3/body.rs
- crates/http/src/backend/h3/mod.rs
- crates/http/src/body.rs
- crates/http/src/error.rs
- crates/workspace-hack/Cargo.toml
- Update to `h3` to `0.0.8`
- Update `h3-quinn` to `0.0.10`
> chore(http): update h3

- crates/tinc/pb-prost/annotations.proto
- crates/tinc/pb-prost/build.rs
- crates/tinc/pb-prost/src/lib.rs
> fix pb prost build

- dev-tools/xtask/src/cmd/workspace_deps.rs
Cargo is stupid...
So because dev-dependencies are allowed to have cycles (this makes sense since they don't effect the build tree of downstream crates) cargo struggles to find the right order to publish because for some reason each dev-dependency must be on crates.io prior to the publish succeeding (this does not make sense).
> fix workspace deps

- crates/batching/Cargo.toml
- crates/context/Cargo.toml
- crates/signal/Cargo.toml
> fix versions

- .github/workflows/cargo-release-pr.yaml
- .github/workflows/release.yaml
some small misses from the previous pr
> fix release

- .github/actions/ci/release-checks/action.yaml
- .github/workflows/cargo-release-pr.yaml
- Justfile
- release-plz.toml
* fix changelog missing from gh releases
* fix missing triggered by from crate release pr
* fixes issue with release-checker failing due to not having full git commit history
> minor fixes found post-release

- Cargo.lock
- crates/openapiv3_1/Cargo.toml
> test bump 2

- .github/actions/ci/release-checks/action.yaml
- .github/workflows/cargo-release-pr.yaml
- dev-tools/xtask/src/cmd/release/check.rs
- dev-tools/xtask/src/cmd/release/utils.rs
- dev-tools/xtask/src/utils.rs
Adds the ability to see when crate versions are bumped / or new crates added or when crates are removed.
> add ability to show crate meta changes

- dev-tools/xtask/src/cmd/release/check.rs
Disables color output for release checks min versions.
Also fixes a slight alignment issue.
> fix release checks color output

- .github/actions/ci/clippy/action.yaml
- .github/actions/ci/grind/action.yaml
- .github/actions/ci/test/action.yaml
- .github/actions/setup-ffmpeg/action.yaml
- .github/actions/setup-rust/action.yaml
- .github/actions/setup-rust/matcher.json
- .github/scripts/ci-matrix-prep.py
- .github/workflows/cargo-release-pr.yaml
- .github/workflows/ci.yaml
- .gitignore
* switches all linux images to be ubuntu 24.04 
* adds windows-arm64 support.
* use stable instead of nightly in ci runs
> new ci images

- dev-tools/xtask/src/cmd/release/check.rs
- dev-tools/xtask/src/cmd/release/update.rs
- dev-tools/xtask/src/cmd/release/utils.rs
* fixes a bug related to packages which are not relaseable not being versions not being bumped.
* fixes an issue causing group deps to always be breaking
* fixes an issue causing unpublish deps to never report changes.
> fix release bumps

- Cargo.lock
- changes.d/pr-511.toml
- crates/tinc/Cargo.toml
- crates/tinc/build/Cargo.toml
- crates/tinc/build/src/lib.rs
- crates/tinc/integration/Cargo.toml
- crates/tinc/pb-prost/Cargo.toml
- crates/tinc/src/lib.rs
- crates/workspace-hack/Cargo.toml
- dev-tools/xtask/src/cmd/release/check.rs
bump prost to 0.14
Since the release of tonic 0.14 we can now upgrade prost.
> upgrade prost

- .github/workflows/cargo-update-pr.yaml
- Justfile
> fix update pr

- .github/workflows/ci-rustdoc.yaml
- .github/workflows/release.yaml
> fix issue release + pr comment

- vendor/BUILD.bazel
stop vendor from compiling from source
> fix cargo vendor

- misc/utils/rust/clippy.bzl
- misc/utils/rust/package.bzl
adds some options to expose rustc flags / rustc env
cc @lennartkloock
> expose rustc flags

- tools/scripts/utils/tool.sh
This should clear the file not append.
> fix tool builds

- Cargo.lock
- Cargo.toml
- Justfile
- MODULE.bazel.lock
- cargo_targets.bzl
- cloud/core/src/bin/standalone.rs
- cloud/email/BUILD.bazel
- cloud/email/Cargo.toml
- cloud/email/LICENSE.AGPL-3.0
- cloud/email/README.md
- cloud/email/src/bin/standalone.rs
- cloud/email/src/lib.rs
- cloud/email/src/services/email.rs
- cloud/email/src/services/mod.rs
- vendor/cargo/defs.bzl
Some boilerplate code for the internal email service
> feat(email): scaffolding

- cloud/core/src/operations/users.rs
> fix(core): TOTP register upsert

- Cargo.lock
- MODULE.bazel.lock
- crates/cedar-policy/Cargo.toml
- crates/cedar-policy/codegen/Cargo.toml
- vendor/cargo/defs.bzl
> fix cedar crates publishability
